{-|
Module       : Python
Description  : Builds lines of Python code for the pen plotter.

NOTE: this is the *only* Haskell file where Python syntax should appear.
The compiler in PiqEvaluation.hs builds its output by calling these
functions rather than by writing Python text itself.

Each line calls one of three tiny functions defined in the provided Python
runtime (python/plotter_runtime.py):

    pen_up()          raise the pen
    pen_down()        lower the pen onto the paper
    move_rel(dx, dy)  travel dx mm to the right and dy mm up
-}

module Python where


-- | Python code to raise the pen
penUp :: String
penUp = "pen_up()"


-- | Python code to lower the pen
penDown :: String
penDown = "pen_down()"


-- | Python code to travel by (dx, dy) millimetres relative to the current
--   position. Positive dx is right, positive dy is up. Whether this draws
--   depends on whether the pen is currently up or down.
moveRel :: Double -> Double -> String
moveRel dx dy = "move_rel(" ++ show dx ++ ", " ++ show dy ++ ")"


--------------------------------------------------------------------------------
-- Complete Python programs
--------------------------------------------------------------------------------

-- | Wraps compiled drawing code into a complete, runnable Python program.
--   The first argument is the folder containing plotter_runtime.py; the
--   program adds it to Python's search path, so the program can be run from
--   any folder. The drawing code runs inside try/finally, so that even if it
--   fails partway through, finish() still raises the pen and disconnects.
pythonProgram :: FilePath -> [String] -> String
pythonProgram runtimeDir code = unlines (header ++ map indent code ++ footer)
    where
        header = [ "# Generated by the piq compiler. Run it with python3:"
                 , "#   python <this file>                         preview in a window"
                 , "#   python <this file> --nowindow --out x.png  save a preview image"
                 , "#   python <this file> --doplot                draw on the real plotter (in the lab)"
                 , ""
                 , "import sys"
                 , "sys.path.insert(0, " ++ pythonString runtimeDir ++ ")"
                 , "from plotter_runtime import start, finish, pen_up, pen_down, move_rel"
                 , ""
                 , "start()"
                 , "try:"
                 ]
        footer = [ "    pass"          -- keeps the program valid if there is no drawing code
                 , "finally:"
                 , "    finish()"
                 ]
        indent line = "    " ++ line


-- | A Python string literal. Haskell's `show` writes a string in double
--   quotes with backslash escapes, which Python reads the same way for
--   ordinary (ASCII) text such as file paths.
pythonString :: String -> String
pythonString text = show text


-- | Writes compiled drawing code to a runnable Python file. The first
--   argument is the folder containing plotter_runtime.py.
emitPython :: FilePath -> FilePath -> [String] -> IO ()
emitPython runtimeDir filename code =
    do let program = pythonProgram runtimeDir code
       -- Haskell is lazy: without this, writeFile could write half the file
       -- before reaching an error (such as an undefined variable) in the
       -- drawing code. Computing the length builds the whole program first,
       -- so a bad program produces no file at all.
       length program `seq` putStrLn ("Writing " ++ filename)
       writeFile filename program
