"""Runtime for Python programs generated by the piq compiler.

Generated programs call only the five functions defined here:

    start()           connect to the plotter and go to the starting point
    pen_up()          raise the pen
    pen_down()        lower the pen
    move_rel(dx, dy)  travel dx mm right and dy mm up (draws only if the pen is down)
    finish()          raise the pen, go home, disconnect

This is the ONE place that talks to the NextDraw API. To change how the
plotter is driven, change this file; the Haskell compiler need not change.

By default nothing physical happens: nextdraw_backend picks the mock
previewer unless the program is run with --doplot. Other flags:
--png / --pdf save a preview image, and --nowindow skips the live preview
window (see mock_nextdraw.py).
"""

from nextdraw_backend import NextDraw, maybe_export

MM_PER_INCH = 25.4

# NextDraw 1117 travel area, in inches. Drawing starts at the page centre so
# that shapes centred on the starting point stay on the page.
PAGE_WIDTH_IN = 16.93
PAGE_HEIGHT_IN = 11.69
START_X_IN = PAGE_WIDTH_IN / 2
START_Y_IN = PAGE_HEIGHT_IN / 2

_nd = None


def connect_plotter():
    '''Create and connect a NextDraw 1117 (real or mock, as nextdraw_backend
    chose), in interactive mode. Stops with advice if it can't connect.'''
    nd = NextDraw()
    nd.interactive()
    nd.options.model = 9  # NextDraw 1117
    if not nd.connect():
        raise SystemExit(
            "Could not connect to NextDraw. Is it plugged in and powered on?\n"
            "On Linux the usual cause is 'Permission denied' on /dev/ttyACM0:\n"
            "your login session is not in the 'dialout' group yet. Either log\n"
            "out and back in, or run the same command inside:\n"
            "    sg dialout -c \"<your command>\"")
    return nd


def start():
    global _nd
    _nd = connect_plotter()
    _nd.moveto(START_X_IN, START_Y_IN)


def pen_up():
    _nd.penup()


def pen_down():
    _nd.pendown()


def move_rel(dx, dy):
    # The compiler uses millimetres with y pointing up the page. The NextDraw
    # uses inches with y pointing down the page. `go` moves relative to the
    # current position and keeps the pen up or down as it is.
    _nd.go(dx / MM_PER_INCH, -dy / MM_PER_INCH)


def finish():
    # Runs even if the drawing code failed, so the pen is never left down.
    if _nd is None:
        return
    _nd.penup()
    _nd.moveto(0, 0)
    maybe_export(_nd)
    _nd.disconnect()
