"""Runtime for Python programs generated by the piq compiler.

Generated programs call only the five functions defined here:

    start()           begin a drawing at the centre of the paper
    pen_up()          raise the pen
    pen_down()        lower the pen
    move_rel(dx, dy)  travel dx mm right and dy mm up (draws only if the pen is down)
    finish()          check the drawing, draw it, go home, disconnect

This is the ONE place that talks to the NextDraw API. To change how the
plotter is driven, change this file; the Haskell compiler need not change.

THE SAFE AREA. The paper is 17 x 11 inches, and the pen must stay at least
1 inch away from its edges: within 190.5 mm left/right and 114.3 mm up/down
of the starting point (the centre of the paper). This applies to every move
between start() and finish(), pen up or down. To make sure a drawing never
stops halfway, nothing is sent to the plotter while the program runs: the
commands are RECORDED, and finish() checks the whole drawing first.
  * Inside the safe area: finish() draws it.
  * Outside, on the real plotter (--doplot): finish() refuses, explains
    where the drawing goes too far, and the pen never moves.
  * Outside, in a preview: the preview is still drawn, with the offending
    moves in red, and a warning says the real plotter would refuse it.
If the drawing code itself crashes, the real plotter draws nothing; a preview
shows the part that was recorded.

By default nothing physical happens: nextdraw_backend picks the mock
previewer unless the program is run with --doplot. Other flags:
--png / --pdf save a preview image, and --nowindow skips the live preview
window (see mock_nextdraw.py).
"""

import sys

from nextdraw_backend import NextDraw, maybe_export, using_real_plotter

MM_PER_INCH = 25.4

# NextDraw 1117 travel area, in inches, from the home corner (top left).
PAGE_WIDTH_IN = 16.93
PAGE_HEIGHT_IN = 11.69

# The paper (17 x 11 inches) sits at the home corner. Drawing starts at its
# centre, and must stay MARGIN_IN inches away from its edges.
PAPER_WIDTH_IN = 17.0
PAPER_HEIGHT_IN = 11.0
MARGIN_IN = 1.0
START_X_IN = PAPER_WIDTH_IN / 2
START_Y_IN = PAPER_HEIGHT_IN / 2

# The safe area, in mm from the starting point: |x| and |y| at most these.
SAFE_HALF_WIDTH_MM = (PAPER_WIDTH_IN / 2 - MARGIN_IN) * MM_PER_INCH      # 190.5
SAFE_HALF_HEIGHT_MM = (PAPER_HEIGHT_IN / 2 - MARGIN_IN) * MM_PER_INCH    # 114.3

# The safe area in the plotter's own coordinates (inches from the home
# corner, y increasing DOWN the page): (left, top, right, bottom).
SAFE_AREA_IN = (MARGIN_IN, MARGIN_IN,
                PAPER_WIDTH_IN - MARGIN_IN, PAPER_HEIGHT_IN - MARGIN_IN)

# Rounding slack, so that a move landing exactly on the limit is allowed.
TOLERANCE_MM = 1e-6

_commands = None    # the recorded drawing: ("up",), ("down",), ("move", dx, dy)
_x = _y = 0.0       # where the pen is, in mm from the start
_overshoot = {}     # edge name -> the furthest distance (mm) past that edge
_nd = None


def connect_plotter():
    '''Create and connect a NextDraw 1117 (real or mock, as nextdraw_backend
    chose), in interactive mode. Stops with advice if it can't connect.'''
    nd = NextDraw()
    nd.interactive()
    nd.options.model = 9  # NextDraw 1117
    if not nd.connect():
        raise SystemExit(
            "Could not connect to NextDraw. Is it plugged in and powered on?\n"
            "On Linux the usual cause is 'Permission denied' on /dev/ttyACM0:\n"
            "your login session is not in the 'dialout' group yet. Either log\n"
            "out and back in, or run the same command inside:\n"
            "    sg dialout -c \"<your command>\"")
    return nd


def start():
    global _commands, _x, _y, _overshoot
    _commands = []
    _x = _y = 0.0
    _overshoot = {}


def pen_up():
    _commands.append(("up",))


def pen_down():
    _commands.append(("down",))


def move_rel(dx, dy):
    # Units are millimetres, with y pointing up the page.
    global _x, _y
    _commands.append(("move", dx, dy))
    _x += dx
    _y += dy
    _check_position()


def _check_position():
    '''Record how far (if at all) the pen is past each edge of the safe area.'''
    for edge, past in (("RIGHT", _x - SAFE_HALF_WIDTH_MM),
                       ("LEFT", -_x - SAFE_HALF_WIDTH_MM),
                       ("TOP", _y - SAFE_HALF_HEIGHT_MM),
                       ("BOTTOM", -_y - SAFE_HALF_HEIGHT_MM)):
        if past > TOLERANCE_MM:
            _overshoot[edge] = max(past, _overshoot.get(edge, 0.0))


def _safe_area_report():
    edges = ", ".join(f"{past:.1f} mm past the {edge} edge"
                      for edge, past in sorted(_overshoot.items()))
    return (f"the drawing leaves the safe area: it goes {edges}.\n"
            f"Every move must stay within {SAFE_HALF_WIDTH_MM:.1f} mm left/right and "
            f"{SAFE_HALF_HEIGHT_MM:.1f} mm up/down of the starting point\n"
            f"(1 inch inside the edges of the paper).")


def finish():
    # Runs even if the drawing code failed (it is called from a `finally`).
    global _nd
    if _commands is None:
        return
    crashed = sys.exc_info()[0] is not None
    if using_real_plotter():
        if crashed:
            print("[plotter_runtime] The drawing code failed, so nothing was plotted.",
                  file=sys.stderr)
            return
        if _overshoot:
            raise SystemExit("[plotter_runtime] NOT PLOTTED: " + _safe_area_report())
    elif _overshoot:
        print("[plotter_runtime] WARNING: " + _safe_area_report() +
              "\nThe moves outside it are drawn in red. The real plotter would refuse "
              "to draw this.", file=sys.stderr)

    _nd = connect_plotter()
    if hasattr(_nd, "set_safe_area"):           # only the mock previewer has this
        _nd.set_safe_area(SAFE_AREA_IN)
    _nd.moveto(START_X_IN, START_Y_IN)
    if hasattr(_nd, "begin_drawing"):
        _nd.begin_drawing()
    for command in _commands:
        if command[0] == "up":
            _nd.penup()
        elif command[0] == "down":
            _nd.pendown()
        else:
            # The NextDraw uses inches with y pointing DOWN the page. `go`
            # moves relative to the current position and keeps the pen up or
            # down as it is.
            _, dx, dy = command
            _nd.go(dx / MM_PER_INCH, -dy / MM_PER_INCH)
    _nd.penup()
    if hasattr(_nd, "end_drawing"):
        _nd.end_drawing()
    _nd.moveto(0, 0)
    maybe_export(_nd)
    _nd.disconnect()
